[project]
name = "spotify-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pablo Bagano", email = "pablobagano@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
spotify-app = "spotify_app:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
